--Eliminar tabla
DROP TABLE ALUMNO;

--Crear tabla
CREATE TABLE ALUMNO( 
    CODIGO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PROMEDIO NUMBER(4,2)
);

--Agregar tupla
INSERT INTO ALUMNO VALUES(100, 'JUAN PEREZ', 12.3);
INSERT INTO ALUMNO VALUES(200, 'PEDRO ALVAREZ', 18.4);
INSERT INTO ALUMNO VALUES(300, 'SARA SANCHEZ', 19.3);

--Mostrar tuplas
SELECT * FROM ALUMNO;

--Mostrar solo algunas columnas (proyeccion)
SELECT NOMBRE, PROMEDIO FROM ALUMNO;

--Mostrar solo algunas tuplas (seleccion)
SELECT * FROM ALUMNO WHERE PROMEDIO > 14;
SELECT * FROM ALUMNO WHERE NOMBRE = 'JUAN PEREZ';

--INCREMENTAR EN 1 EL PROMEDIO DEL ALUMNO DE CODIGO 100
UPDATE ALUMNO SET PROMEDIO = PROMEDIO + 1 WHERE CODIGO = 100;
    
--ELIMINAR LA TUPLA CORRESPONDIENTE AL ALUMNO DE CODIGO 200
DELETE FROM ALUMNO WHERE CODIGO = 200;


