/*
    TABLAS DEL SISTEMA
    DDL
*/
--ELIMINAMOS TABLAS
DROP TABLE PARTICIPACION;
DROP TABLE USUARIO;
DROP TABLE CAMPEONATO;
DROP TABLE EQUIPO;


CREATE TABLE EQUIPO(
    COD_EQUIPO NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);

INSERT INTO EQUIPO VALUES(1, 'LAS AGUILAS');
INSERT INTO EQUIPO(COD_EQUIPO, NOMBRE) VALUES (40, 'AVENGERS');

CREATE TABLE USUARIO(
    CODIGO NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    COD_EQUIPO REFERENCES EQUIPO
);

INSERT INTO USUARIO VALUES(100, 'JUAN PEREZ', 1);
INSERT INTO USUARIO(CODIGO, NOMBRE) VALUES(200, 'CESAR PERALES');
INSERT INTO USUARIO VALUES(300, 'MARIA VALENCIA', 40);


CREATE TABLE CAMPEONATO(
    CODIGO NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

INSERT INTO CAMPEONATO VALUES(1, 'NACIONAL ARGENTINA', SYSDATE, SYSDATE + 6);
INSERT INTO CAMPEONATO VALUES(2, 'CAMPEONATO MUNDIAL', '01-JAN-20', '07-JAN-20');
INSERT INTO CAMPEONATO VALUES(3, 'ELIMINATORIAS EUROPA', TO_DATE('10/05/2008', 'DD/MM/YYYY'), TO_DATE('15/05/2008', 'DD/MM/YYYY'));
INSERT INTO CAMPEONATO VALUES(4, 'CAMPEONATO PERUANO', TO_DATE('01/02/2010', 'DD/MM/YYYY'), TO_DATE('07/02/2010', 'DD/MM/YYYY'));

--EJEMPLOS ALTER TABLE
/*
ALTER TABLE CAMPEONATO ADD FECHA_FIN DATE;
ALTER TABLE CAMPEONATO DROP COLUMN FECHA;
ALTER TABLE CAMPEONATO ADD FECHA_INICIO DATE;
ALTER TABLE CAMPEONATO RENAME COLUMN FECHA_INICIO TO FECHA_INI;
*/


CREATE TABLE PARTICIPACION(
    COD_USUARIO REFERENCES USUARIO,
    COD_CAMPEONATO REFERENCES CAMPEONATO,
    RESULTADO VARCHAR2(40),
    PRIMARY KEY(COD_USUARIO, COD_CAMPEONATO)
);

INSERT INTO PARTICIPACION VALUES(100, 1, 'GANADOR');
INSERT INTO PARTICIPACION VALUES(200, 1, 'PARTICIPANTE');
INSERT INTO PARTICIPACION VALUES(200, 2, 'GANADOR');

--CONSULTAS
SELECT * FROM USUARIO;
SELECT * FROM CAMPEONATO;

SELECT * FROM CAMPEONATO
WHERE FECHA_FIN - FECHA_INICIO = 6;

SELECT FECHA, FECHA + 66 FROM CAMPEONATO;


--OBTENER NOMBRE USUARIO, EL NOMBRE DEL CAMPEONATO Y EL RESULTADO
SELECT  U.NOMBRE AS NOMBRE_USUARIO, C.NOMBRE AS NOMBRE_CAMPEONATO, P.RESULTADO
FROM PARTICIPACION P, USUARIO U, CAMPEONATO C
WHERE P.COD_USUARIO = U.CODIGO
AND P.COD_CAMPEONATO = C.CODIGO;

--OBTENER NOMBRE USUARIO, NOMBRE DEL EQUIPO, EL NOMBRE DEL CAMPEONATO Y EL RESULTADO
SELECT U.NOMBRE AS NOMBRE_USUARIO, E.NOMBRE AS NOMBRE_EQUIPO, C.NOMBRE AS NOMBRE_CAMPEONATO, P.RESULTADO
FROM PARTICIPACION P, USUARIO U, CAMPEONATO C, EQUIPO E
WHERE P.COD_USUARIO = U.CODIGO
AND P.COD_CAMPEONATO = C.CODIGO
AND U.COD_EQUIPO = E.COD_EQUIPO;


